(ns clothing.prompts)

(def prompts
  ["Feeling like a disco ball."
   "Embracing your inner cactus."
   "Today's mood: radioactive unicorn."
   "Just escaped from a 90's music video."
   "Dressed by aliens... again."
   "\"Oops! I spilled magic.\""
   "Channeling my inner potato."
   "Attending a yeti's summer party."
   "If Picasso painted an outfit."
   "Fresh out of a fairy tale."
   "Woke up in the Matrix."
   "Wizard on a coffee break."
   "Ninja, but make it fashion."
   "My socks rule the galaxy."
   "Serving \"lost in a board game\" vibes."
   "Part-time mermaid."
   "Undercover superhero day-off."
   "Bedhead ambassador."
   "Dressed by spaghetti."
   "Astronaut's beach day."
   "Dinosaur's first date look."
   "Pirate's pajama party."
   "If Monday was an outfit."
   "Retro-futuristic cowpoke."
   "Midsummer night's dreamer."])
